#!/bin/busybox sh
bb=/bin/busybox
case "$1" in
deconfig) $bb ifconfig "$interface" 0.0.0.0 ;;
bound|renew)
    $bb ifconfig "$interface" "$ip" netmask "${subnet:-255.255.255.0}" up
    $bb route del default dev "$interface" 2>/dev/null || :
    for gateway in $router; do $bb route add default gw "$gateway" dev "$interface"; done
    : >/run/resolv.conf
    for server in $dns; do echo "nameserver $server" >>/run/resolv.conf; done
    ;;
esac
